### ISSUE TITLE
memory_provisionable_bytes not present where expected

### ISSUE THREAD

**Issue by dsockwell** [joyent/sdc-cnapi#12]
On my new install of Triton, the Admin UI reports NaN% provisionable RAM for my one compute node.

Bahamat assisted me with some information gathering on IRC, which I'll post in rough Q&A format:

> 01:41 dsockwell> so I have a Triton compute node reporting NaN bytes provisionable from the admin UI's 'servers' list and then from its detail page, NaN% utilization and 0 bytes provisionable. The node has 128G of RAM installed and I just set it up according to the instructions. Is this a known mode of failure?
> 01:46 dsockwell> provisioning a vm fails with 'no compute resources available' which is the opposite of what i wanted when i set this server up
> 04:12 bahamat> dsockwell: Can you show me the output of this command? sdc-cnapi /servers?extras=capacity | json -Ha hostname unreserved_ram
> 04:17 dsockwell> 00-25-90-85-73-ea 111374
> 04:17 dsockwell> headnode -19395
> 04:20 bahamat> And can you give me a screenshot of the nan thing you're seeing?
> 04:22 dsockwell> http://i.imgur.com/koEMwCD.png
> 04:23 bahamat> dsockwell: And what version of adminui are you running? (from the headnode run `sdcadm insts adminui`)
> 04:24 dsockwell> bbfaaed7-e3ca-4772-9ad5-125cb88e09e8  adminui  headnode  release-20190314-20190314T050848Z-g9296c5b  adminui0
> 04:25 bahamat> Hmm. I'm running the exact same version and I'm not seeing that problem.
> 04:26 bahamat> Does it say that for every CN, or just the one?
> 04:27 dsockwell> from memory, the headnode's page is also odd. 73-ea is the only compute node configured now.
> 04:28 bahamat> dsockwell: Can you show me this as well? sdc-cnapi /servers?extras=capacity | json -Ha hostname memory_provisionable_bytes
> 04:30 dsockwell> # sdc-cnapi /servers?extras=capacity | json -Ha hostname memory_provisionable_bytes
> 04:30 dsockwell> 00-25-90-85-73-ea
> 04:30 dsockwell> headnode
> 04:31 bahamat> That's what's wrong.
> 04:31 bahamat> You should have a value there and there isn't one.
> 04:31 dsockwell> no bytes does sound like a big deal
> 04:31 bahamat> What version of cn-agent do you have? (sdcadm insts cn-agent)
> 04:31 bahamat> Or sdcadm insts -I cn-agent
> 04:31 dsockwell> 3afdb571-a03a-4481-b91b-73d5fd67b06f  cn-agent  00-25-90-85-73-ea  2.10.1   -
> 04:31 dsockwell> 75a658de-95c1-40df-9233-b262fbefd772  cn-agent  headnode           2.10.1   -
> 04:32 bahamat> Try restarting cn-agent on each CN and see if that helps.
> 04:32 dsockwell> oh thats going to be instance IDs?
> 04:32 dsockwell> cn-agent  1869f458-5ae5-41f0-a3e9-443da9b43934  2.10.1   2
> 04:32 dsockwell> for the second query
> 04:33 bahamat> The version number was really what I needed. Yours is up to date.
> 04:35 dsockwell> i have previously rebooted both machines entirely and gotten the same output
> 04:37 bahamat> I just need to know if there's any output to that command.
> 04:37 bahamat> If there is, then you're failing here: https://github.com/joyent/sdc-cnapi/blob/master/lib/models/server.js#L2045-L2086
> 04:37 bahamat> grep memory_provisionable_bytes $(svcs -ZL cnapi)
> 04:37 dsockwell> no output

![](http://i.imgur.com/koEMwCD.png)

**Comment by dsockwell** [comment]
It now occurs to me that this could be TRITON-1361 since it occurs on 20190314T022529Z which is older than the supposed fix: https://github.com/joyent/sdc-cnapi/commit/ba9d19aec855d992217bb10e079671c915fbe342

I'm attempting to upgrade my cluster to release-20190328-20190328T145412Z to see if it resolves the problem.

**Comment by dsockwell** [comment]
Switching to the newer platform image didn't help, but afterward I manually applied the below-listed patch to /opt/smartdc/cnapi/lib/models and restarted cnapi and now the Admin UI displays a real, plausible number for provisionable RAM on each node including the head node.

https://github.com/joyent/sdc-cnapi/commit/ba9d19aec855d992217bb10e079671c915fbe342#diff-1fea01e1fa24bbcec21dc7e1386e96beL2050

**Comment by bahamat** [comment]
This turned out to be TRITON-1361, which was recently fixed as noted by @dsockwell.
